class AppError extends Error {
    constructor(message, statusCode) {
        super(message);

        this.statusCode = statusCode;
        this.status = this.statusCode.toString().startsWith(4) ? 'fail' : 'err'; //change this.statusCode to statusCode if something breaks
        this.operational = true; //basically means it is an operational error generated by the user and not a progmatic error

        Error.captureStackTrace(this, this.constructor); //this to catch stack trace of the error, from where it is originated
    }
}

module.exports = AppError;
